import"./assets/vendor-6837a909.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const y=["Animated","the adventures","Justin Roiland","superpower","creative","amazing","Sitcom","comics","follows","characters","whoa","Rick and Morty"],E=document.getElementById("divider");y.forEach((n,s)=>{const e=document.createElement("span");e.textContent=n,e.className=`chip ${s%2===0?"light":"dark"}`;const t=(Math.random()>.6?180:0)+(Math.random()*30-15);e.style.setProperty("--angle",`${t}deg`),e.style.animationDelay=`${Math.random()*2}s`,E.appendChild(e)});const v="https://rickandmortyapi.com/api/episode",l=document.getElementById("episodesContainer"),m=document.getElementById("loadMoreBtn"),h=document.getElementById("selectSeason"),g=document.getElementById("searchName"),L=document.getElementById("searchBtn");let i=[],c=[],a=20;async function w(){try{let n=v;for(;n;){const e=await(await fetch(n)).json();i.push(...e.results),n=e.info.next}i=i.filter(s=>{const e=s.episode.slice(0,3);return["S01","S02","S03","S04","S05"].includes(e)}),c=i,u()}catch(n){console.error("Error fetching episodes:",n),p(!0)}}function u(){l.innerHTML="";const n=c.slice(0,a);if(n.length===0){p(!0);return}p(!1),n.forEach(s=>{const e=document.createElement("div");e.classList.add("episode-card"),e.innerHTML=`
      <img src="images/season-corect.png" alt="${s.name}" onerror="this.src='img/portal.png'">
      <div class="episode-info">
        <h3>${s.name}</h3>
        <p>Season: ${s.episode.slice(1,3)}</p>
        <p>Air date: ${s.air_date}</p>
      </div>
    `,l.appendChild(e)}),m.style.display=c.length>a?"block":"none"}function f(){const n=h.value,s=g.value.trim().toLowerCase();c=i.filter(e=>{const r=n==="all"||e.episode.startsWith(n),t=e.name.toLowerCase().includes(s);return r&&t}),a=20,u()}function p(n){n&&(l.innerHTML=`
      <div class="placeholder">
        <img src="images/portal.png" alt="Portal" />
        <p>Oops! Try looking for something else...</p>
      </div>
    `,m.style.display="none")}m.addEventListener("click",()=>{a+=20,u()});h.addEventListener("change",f);L.addEventListener("click",f);g.addEventListener("keydown",n=>{n.key==="Enter"&&f()});w();
//# sourceMappingURL=commonHelpers.js.map
